angular.module('app', ['ui.bootstrap'])
    .controller('DataController', function() {
       var now = new Date();
       this.items = [
           {
               id: 123456,
               number: '123abc',
               date1: now,
               date2: now,
               date3: now,
               authority: 'ACME Inc.',
               concern: 'big fires',
               attachment: 'Overly Attached',
               region: 'Western Pennsylvania',
               system: '800000',
               systemName: 'Metamucil (lots of fiber)',
               city: 'Pittsburgh',
               another1: 'Some med field',
               another2: 'Very late. Much data.',
               another3: 1234564789,
               status: 'standing',
               state: 'PA'
           },
           {
               id: 123456,
               number: '123abc',
               date1: now,
               date2: now,
               date3: now,
               authority: 'ACME Inc.',
               concern: 'big fires',
               attachment: 'Overly Attached',
               region: 'Western Pennsylvania',
               system: '800000',
               systemName: 'Metamucil (lots of fiber)',
               city: 'Pittsburgh',
               another1: 'Some med field',
               another2: 'Very late. Much data.',
               another3: 1234564789,
               status: 'standing',
               state: 'PA'
           },
           {
               id: 123456,
               number: '123abc',
               date1: now,
               date2: now,
               date3: now,
               authority: 'ACME Inc.',
               concern: 'big fires',
               attachment: 'Overly Attached',
               region: 'Western Pennsylvania',
               system: '800000',
               systemName: 'Metamucil (lots of fiber)',
               city: 'Pittsburgh',
               another1: 'Some med field',
               another2: 'Very late. Much data.',
               another3: 1234564789,
               status: 'standing',
               state: 'PA'
           },
           {
               id: 123456,
               number: '123abc',
               date1: now,
               date2: now,
               date3: now,
               authority: 'ACME Inc.',
               concern: 'big fires',
               attachment: 'Overly Attached',
               region: 'Western Pennsylvania',
               system: '800000',
               systemName: 'Metamucil (lots of fiber)',
               city: 'Pittsburgh',
               another1: 'Some med field',
               another2: 'Very late. Much data.',
               another3: 1234564789,
               status: 'standing',
               state: 'PA'
           },
           {
               id: 123456,
               number: '123abc',
               date1: now,
               date2: now,
               date3: now,
               authority: 'ACME Inc.',
               concern: 'big fires',
               attachment: 'Overly Attached',
               region: 'Western Pennsylvania',
               system: '800000',
               systemName: 'Metamucil (lots of fiber)',
               city: 'Pittsburgh',
               another1: 'Some med field',
               another2: 'Very late. Much data.',
               another3: 1234564789,
               status: 'standing',
               state: 'PA'
           },
           {
               id: 123456,
               number: '123abc',
               date1: now,
               date2: now,
               date3: now,
               authority: 'ACME Inc.',
               concern: 'big fires',
               attachment: 'Overly Attached',
               region: 'Western Pennsylvania',
               system: '800000',
               systemName: 'Metamucil (lots of fiber)',
               city: 'Pittsburgh',
               another1: 'Some med field',
               another2: 'Very late. Much data.',
               another3: 1234564789,
               status: 'standing',
               state: 'PA'
           },
           {
               id: 123456,
               number: '123abc',
               date1: now,
               date2: now,
               date3: now,
               authority: 'ACME Inc.',
               concern: 'big fires',
               attachment: 'Overly Attached',
               region: 'Western Pennsylvania',
               system: '800000',
               systemName: 'Metamucil (lots of fiber)',
               city: 'Pittsburgh',
               another1: 'Some med field',
               another2: 'Very late. Much data.',
               another3: 1234564789,
               status: 'standing',
               state: 'PA'
           },
           {
               id: 123456,
               number: '123abc',
               date1: now,
               date2: now,
               date3: now,
               authority: 'ACME Inc.',
               concern: 'big fires',
               attachment: 'Overly Attached',
               region: 'Western Pennsylvania',
               system: '800000',
               systemName: 'Metamucil (lots of fiber)',
               city: 'Pittsburgh',
               another1: 'Some med field',
               another2: 'Very late. Much data.',
               another3: 1234564789,
               status: 'standing',
               state: 'PA'
           },
           {
               id: 123456,
               number: '123abc',
               date1: now,
               date2: now,
               date3: now,
               authority: 'ACME Inc.',
               concern: 'big fires',
               attachment: 'Overly Attached',
               region: 'Western Pennsylvania',
               system: '800000',
               systemName: 'Metamucil (lots of fiber)',
               city: 'Pittsburgh',
               another1: 'Some med field',
               another2: 'Very late. Much data.',
               another3: 1234564789,
               status: 'standing',
               state: 'PA'
           },
           {
               id: 123456,
               number: '123abc',
               date1: now,
               date2: now,
               date3: now,
               authority: 'ACME Inc.',
               concern: 'big fires',
               attachment: 'Overly Attached',
               region: 'Western Pennsylvania',
               system: '800000',
               systemName: 'Metamucil (lots of fiber)',
               city: 'Pittsburgh',
               another1: 'Some med field',
               another2: 'Very late. Much data.',
               another3: 1234564789,
               status: 'standing',
               state: 'PA'
           }
       ];
    });